# Generated by Django 5.2.6 on 2025-10-24 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SpecializationName', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StaffId', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('Role', models.CharField(choices=[('ADMIN', 'Administrator'), ('REC', 'Receptionist'), ('DOC', 'Doctor'), ('PHM', 'Pharmacist'), ('LTECH', 'Lab Technician')], max_length=10)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('BloodGroup', models.CharField(max_length=3)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=15)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['StaffId'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('ConsultationFee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ConsultationDays', models.CharField(help_text='Eg: Monday-Friday (or) Monday, Tuesday, Friday', max_length=100)),
                ('ConsultationTime', models.CharField(help_text='Eg: 9:00 AM - 5:00 PM', max_length=100)),
                ('YearsOfExperience', models.PositiveIntegerField(default=0)),
                ('IsAvailable', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('SpecializationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_backend_app.specialization')),
                ('StaffId', models.OneToOneField(limit_choices_to={'Role': 'DOC'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='admin_backend_app.staff')),
            ],
        ),
    ]
