# Generated by Django 5.2.6 on 2025-10-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consultationId', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('AppointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='receptionist_backend_app.appointment')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['consultationId'],
            },
        ),
        migrations.CreateModel(
            name='LabPrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('labPrescriptionId', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_prescriptions', to='doctor_backend_app.consultation')),
            ],
            options={
                'verbose_name': 'Lab Prescription',
                'verbose_name_plural': 'Lab Prescriptions',
                'ordering': ['labPrescriptionId'],
            },
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medPrescriptionId', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_prescriptions', to='doctor_backend_app.consultation')),
            ],
            options={
                'verbose_name': 'Medicine Prescription',
                'verbose_name_plural': 'Medicine Prescriptions',
                'ordering': ['medPrescriptionId'],
            },
        ),
    ]
