# Generated by Django 5.2.6 on 2025-10-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='Notes',
            field=models.TextField(blank=True, help_text="Doctor's notes for this consultation", null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='IN_PROGRESS', max_length=20),
        ),
    ]
