# Generated by Django 5.2.6 on 2025-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_backend_app', '0002_consultation_notes_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprescription',
            name='Notes',
            field=models.TextField(blank=True, help_text="Doctor's notes for this lab test prescription", null=True),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='Notes',
            field=models.TextField(blank=True, help_text="Doctor's notes for this medicine prescription", null=True),
        ),
    ]
