# Generated by Django 5.2.6 on 2025-10-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_backend_app', '0003_labprescription_notes_medicineprescription_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprescription',
            name='test_fasting_required',
            field=models.BooleanField(default=False, help_text='Whether fasting is required before the test'),
        ),
        migrations.AddField(
            model_name='labprescription',
            name='test_instructions',
            field=models.TextField(blank=True, help_text='Special instructions for the test', null=True),
        ),
        migrations.AddField(
            model_name='labprescription',
            name='test_name',
            field=models.CharField(blank=True, help_text='Name of the lab test', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labprescription',
            name='test_type',
            field=models.CharField(blank=True, help_text='Type of lab test (Blood, Urine, etc.)', max_length=100, null=True),
        ),
    ]
