# Generated by Django 5.2.6 on 2025-10-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_backend_app', '0004_labprescription_test_fasting_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(help_text='Name of the lab test', max_length=200, unique=True)),
                ('test_type', models.CharField(help_text='Type of lab test (Blood, Urine, etc.)', max_length=100)),
                ('test_instructions', models.TextField(help_text='Default instructions for the test')),
                ('test_fasting_required', models.BooleanField(default=False, help_text='Whether fasting is required before the test')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this test is available for prescription')),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['test_name'],
            },
        ),
        migrations.RemoveField(
            model_name='labprescription',
            name='test_fasting_required',
        ),
        migrations.RemoveField(
            model_name='labprescription',
            name='test_instructions',
        ),
        migrations.RemoveField(
            model_name='labprescription',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='labprescription',
            name='test_type',
        ),
        migrations.AddField(
            model_name='labprescription',
            name='lab_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor_backend_app.labtest'),
        ),
    ]
