# Generated by Django 5.2.6 on 2025-10-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_backend_app', '0005_labtest_remove_labprescription_test_fasting_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprescription',
            name='lab_test',
        ),
        migrations.AddField(
            model_name='labprescription',
            name='test_fasting_required',
            field=models.BooleanField(default=False, help_text='Whether fasting is required before the test'),
        ),
        migrations.AddField(
            model_name='labprescription',
            name='test_instructions',
            field=models.TextField(default='', help_text='Instructions for the test'),
        ),
        migrations.AddField(
            model_name='labprescription',
            name='test_name',
            field=models.CharField(default='', help_text='Name of the lab test', max_length=200),
        ),
        migrations.AddField(
            model_name='labprescription',
            name='test_type',
            field=models.CharField(default='', help_text='Type of lab test (Blood, Urine, etc.)', max_length=100),
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
    ]
