# Generated by Django 5.2.6 on 2025-10-24 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PatientId', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.PositiveIntegerField()),
                ('Height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('Weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('DOB', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('EmergencyNumber', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('IsActive', models.BooleanField(default=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['PatientId'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentId', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('TokenNo', models.PositiveIntegerField()),
                ('Date', models.DateField()),
                ('Status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('DoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='admin_backend_app.doctor')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['AppointmentId'],
            },
        ),
    ]
