# Generated by Django 5.2.6 on 2025-10-24 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='PatientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='receptionist_backend_app.patient'),
        ),
    ]
